version: '3'

services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
    - '5432:5432'
    volumes:
    - db-store:/var/lib/postgresql/data
    - ./database/init:/docker-entrypoint-initdb.d
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
volumes:
  db-store:
