-- Add new schema named "atlas_schema_revisions"
CREATE SCHEMA "atlas_schema_revisions";
-- Add new schema named "public"
CREATE SCHEMA IF NOT EXISTS "public";
-- Set comment to schema: "public"
COMMENT ON SCHEMA "public" IS 'standard public schema';
-- Create "atlas_schema_revisions" table
CREATE TABLE "atlas_schema_revisions"."atlas_schema_revisions" ("version" character varying NOT NULL, "description" character varying NOT NULL, "type" bigint NOT NULL DEFAULT 2, "applied" bigint NOT NULL DEFAULT 0, "total" bigint NOT NULL DEFAULT 0, "executed_at" timestamptz NOT NULL, "execution_time" bigint NOT NULL, "error" text NULL, "error_stmt" text NULL, "hash" character varying NOT NULL, "partial_hashes" jsonb NULL, "operator_version" character varying NOT NULL, PRIMARY KEY ("version"));
-- Create "users" table
CREATE TABLE "public"."users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "age" bigint NOT NULL, "name" character varying NOT NULL DEFAULT 'unknown', PRIMARY KEY ("id"));
-- Create "cards" table
CREATE TABLE "public"."cards" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "number" character varying NOT NULL, "user_card" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "cards_users_card" FOREIGN KEY ("user_card") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "cards_user_card_key" to table: "cards"
CREATE UNIQUE INDEX "cards_user_card_key" ON "public"."cards" ("user_card");
-- Create "cars" table
CREATE TABLE "public"."cars" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "model" character varying NOT NULL, "registered_at" timestamptz NOT NULL, "user_cars" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "cars_users_cars" FOREIGN KEY ("user_cars") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "groups" table
CREATE TABLE "public"."groups" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "group_users" table
CREATE TABLE "public"."group_users" ("group_id" bigint NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("group_id", "user_id"), CONSTRAINT "group_users_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."groups" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "group_users_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "pets" table
CREATE TABLE "public"."pets" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "car_pets" bigint NULL, "user_pets" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "pets_cars_pets" FOREIGN KEY ("car_pets") REFERENCES "public"."cars" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "pets_users_pets" FOREIGN KEY ("user_pets") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
